all:
  children:
    postgresql_servers:
      hosts:
        postgresql_servers_vm:
          ansible_host: 172.16.20.192
          ansible_user: marsel
          ansible_password: "123456^^"
          ansible_become: true
          ansible_become_password: "123456^^"
          ansible_connection: ssh
    # exporters:
    #   hosts:
    #     # Добавьте сюда хосты с экспортерами
